### ISSUE TITLE
Add reference to OCSP? 

### ISSUE THREAD

**Issue by csosto-pk** [lamps-wg/dilithium-certificates#10]
From https://mailarchive.ietf.org/arch/msg/spasm/mHLRo-X8U7ZAF5BRjPEPA8lHQtk/ 

> Should this document also talk about Dilithium signatures in OCSP?  I realize that was not done when RFC 3279 and RFC 5480 were written.
> Russ

**Comment by csosto-pk** [comment]
Hmm, we did not do that RFC8692 recently either. 
But all these identifiers could be used in the SigAlgID in OCSP request/responses or staples as well. 
Probably it makes sense we reference OCSP in the draft.

**Comment by csosto-pk** [comment]
From Tim H.

> I have a slight preference for keeping them separate.  When OCSP and CRLs are discussed in the same document, it's often confusing because they're quite different, and it's difficult to keep clear what applies to one or the other, and what applies to both.

**Comment by seanturner** [comment]
We do need to add the sa- classes so that should get us some of the way there because those can be used by OCSP, PKCS#10, CMP, CMC, etc. But, as I mentioned in #12, we'll end up with some references dependencies we might not want.

**Comment by csosto-pk** [comment]
ACK, I am OK not referencing OCSP in ours.

**Comment by csosto-pk** [comment]
Looking at old drafts, they did not reference OCSP in these documents. We did not do it in RFC8692 recently either.

The identifiers could be used in OCSP, but I think we don't need to mention OCSP. 

Will close this unless there are objections.
