### ISSUE TITLE
'88 or '21 ASN.1

### ISSUE THREAD

**Issue by seanturner** [lamps-wg/dilithium-certificates#15]
In looking at the ML-KEM and ML-DSA I-Ds, they both include the AlgorithmIdentifier syntax for convenience. ML-DSA uses the '88 syntax and ML-KEM uses the '21 syntax:

ML-DSA:

     AlgorithmIdentifier  ::=  SEQUENCE  {
         algorithm   OBJECT IDENTIFIER,
         parameters  ANY DEFINED BY algorithm OPTIONAL
     }

ML-KEM:

    AlgorithmIdentifier{ALGORITHM-TYPE, ALGORITHM-TYPE:AlgorithmSet} ::=
      SEQUENCE {
        algorithm   ALGORITHM-TYPE.&id({AlgorithmSet}),
        parameters  ALGORITHM-TYPE.
                    &Params({AlgorithmSet}{@algorithm}) OPTIONAL
      }

We should pick one for both. I prefer the later syntax because '88 was almost 40 years ago.

**Comment by jakemas** [comment]
Merged in https://github.com/lamps-wg/dilithium-certificates/pull/16
