### ISSUE TITLE
KeyUsage Bits

### ISSUE THREAD

**Issue by seanturner** [lamps-wg/dilithium-certificates#17]
Currently, the I-D says include any of the signing related KUs.  We ended up publishing [RFC8813](https://datatracker.ietf.org/doc/rfc8813/) and [RFC9295](https://datatracker.ietf.org/doc/rfc9295/) to prohibit the use of non-signing KUs.  Should we do the same here?

**Comment by jakemas** [comment]
We absolutely should -- thank you for this call-out. Merged in https://github.com/lamps-wg/dilithium-certificates/pull/18
