### ISSUE TITLE
Add Dilithium-2 paragraph in Security Considerations

### ISSUE THREAD

**Issue by csosto-pk** [lamps-wg/dilithium-certificates#2]
Dilithium-2 offers a CoreSVP hardness of ~118 bits of security which is a little lower than it should. The Kyber submission refines the CoreSVP cost by using sieving cost simulations and claims that the gate and memory cost is ~2^150 and ~2^90 approximately which they argue is better than AES. I think it would be worth to call out the CoreSVP hardness and the refined estimate for Dilithium-2 in the Sec Considerations section.

**Comment by csosto-pk** [comment]
Depending on what gets standardized, this will be of value in the end. In the end, there will only be one Dilithium algorithm, the one specified by NIST with or without the Dilithium-2 parameter.

**Comment by csosto-pk** [comment]
What does the team think about adding a small paragraph about ML-DSA-44 and its <2^128 theoretical security?

**Comment by bwesterb** [comment]
AFAIK there is no demonstration that ML-DSA-44 doesn't reach NIST PQC security level 2 in practice, let alone 1. Security estimates will continue to evolve: practical attacker models will be more refined, and cryptanalysis will continue to improve. I do not think the static security considerations section of an RFC is the best place to speculate on that. It might be helpful to note to the reader that they might want to check out the latest understanding of ML-DSA's security, as it's likely more volatile than that of say SLH-DSA.

**Comment by csosto-pk** [comment]
I can live with that. 
Closing.
