### ISSUE TITLE
Should we use the context string?

### ISSUE THREAD

**Issue by bwesterb** [lamps-wg/dilithium-certificates#24]
Mike asks [which context string](https://mailarchive.ietf.org/arch/msg/spasm/voUR5EXhtd9fvZL1pYRpTvnDTLs/) to use. At the moment we don't set any.

This question is not specific to ML-DSA. Context strings have been discussed in general in [this LAMPS thread](https://mailarchive.ietf.org/arch/msg/spasm/XH_VtuiYt4YWxuDS3dHsR70aQF0/).

**Comment by ounsworth** [comment]
The correct answer is probably to use the empty string. One good reason for this is backwards-compatibility with signature primitives that do not have ctx params, and even with crypto libraries that offer ML-DSA but no not have a `.Sign()` interface that accepts a ctx parameter.

Empty string is already the default in FIPS 204, so in theory nothing needs to be said in draft-dilithium-certificates, but it would probably be polite to put in a sentence.

**Comment by bwesterb** [comment]
There is an argument to be made to set a context string. Over time, the signature algorithms used will all have context. Also, requiring it here forces libraries to adopt it, which is very helpful to protocols where a context string is more useful but don't have the reach of X509. The clear downside is more work and added complexity. I have not made up my mind.

**Comment by jakemas** [comment]
I think we should probably include the context string, as any FIPS implementation of ML-DSA will have it included. However, I do agree that minimizing complexity is important. The use of the empty string seems the most reasonable solution here.

**Comment by csosto-pk** [comment]
I vote for empty string. It does not add anything in the X.509 context. 

If folks insist, a simple context like the ASCII characters of "X.509 ML-DSA" would suffice imo.

**Comment by ounsworth** [comment]
After thinking a bit more, here is a more refined opinion:

What should be in draft-ietf-lamps-dilithium-certificates-05 is a statement that ML-DSA signatures produced by CA certificates (basicConstraints.cA=true) MUST use ctx=””, while signatures produced by end entity certificates MAY use any ctx value as appropriate for its application context.

**Comment by OR13** [comment]
Sorry for hitting the list before seeing this.

For some context regarding JOSE / COSE.

The both already have their own application layer context constructions, so I don't plan to expose ctx directly in the specifications, unless there is clear justification for doing it the same way as this draft.

FWIW, I am in favor of "empty string".

**Comment by ounsworth** [comment]
> For some context regarding JOSE / COSE.
> 
> The both already have their own application layer context constructions, so I don't plan to expose ctx directly in the specifications, unless there is clear justification for doing it the same way as this draft.
> 
> FWIW, I am in favor of "empty string".

Orie,

Another thought. CMS is actually the closer parallel between COSE and “LAMPS-things”.

https://datatracker.ietf.org/doc/html/draft-ietf-lamps-cms-ml-dsa-01

It says:

ML-DSA has a context string input that can be used to ensure that different signatures are generated for different application contexts. When using ML-DSA as described in this document, the context string is not used. 

So ctx=”” everywhere within CMS, mainly because it already has plenty of context binding at the application layer.

**Comment by csosto-pk** [comment]
Context had some value when HashML-DSA was going to be used. I think, now that HashML-DSA is becoming irrelevant there is no point in using ctx. Empty string makes sense to me.

**Comment by csosto-pk** [comment]
Need to close this one, I think we converged to empty ctx.

**Comment by danvangeest** [comment]
> Context had some value when HashML-DSA was going to be used.

@csosto-pk can you expand on this?  Does it also apply to HashSLH-DSA? HashSLH-DSA is being defined for public keys in end-entity certificates, so x509-slhdsa doesn't really have any say about how the context would be use there, but I'm curious why you say the context had some use with HashML-DSA.

**Comment by csosto-pk** [comment]
> > Need to close this one, I think we converged to empty ctx.
> 
> We might still want to add some words to that effect to the I-D.

Please check https://github.com/lamps-wg/dilithium-certificates/pull/62

**Comment by danvangeest** [comment]
@csosto-pk, M` is already constructed differently depending if you're using Hash*-DSA or (pure) *-DSA.  So the context won't add any additional differentiation between pure and Hash signatures.  The value in using the context is if you're signing different content types with the same key and signature algorithm.  Then using different contexts for different content types avoids a potential issue if there are encoding collisions between the content types.

Given that everything that is signed by a CA key is ASN.1 encoded, there shouldn't be any encoding collisions for this draft.

**Comment by csosto-pk** [comment]
ACK, you are right. The OIDs are in there already. Fine by me if you also use empty everywhere.

**Comment by csosto-pk** [comment]
Ready to be closed. The change made it in.
