### ISSUE TITLE
ASN.1 size constraints on public key and private key types

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/dilithium-certificates#53]
See: https://mailarchive.ietf.org/arch/msg/spasm/G45YcgPnTwvqmOJwX6IxLzYA-LI/

**Comment by danvangeest** [comment]
Since this draft relies on the cms-ml-dsa draft for ASN.1, you probably want to follow this instead: https://github.com/lamps-wg/cms-ml-dsa/issues/10

**Comment by seanturner** [comment]
Addressed via #64.
